import type { Plan, PlanStep } from "../agent/types.js";
import type { ToolRegistry } from "../tools/ToolRegistry.js";

export interface BindPlanToolsOptions {
  registry: ToolRegistry;
  defaultReadPath?: string;
}

/**
 * 将骨架 Plan 步骤绑定为可执行 tool + toolInput（Semantic Compiler 的确定性兜底）。
 * Planner 未返回 tool 字段时，compile / revise 路径必须经此绑定后才能 persist。
 */
export function bindPlanTools(plan: Plan, options: BindPlanToolsOptions): Plan {
  const steps = plan.steps.map((step) => bindStep(step, options));
  return { ...plan, steps };
}

function bindStep(step: PlanStep, options: BindPlanToolsOptions): PlanStep {
  if (step.tool && step.toolInput && Object.keys(step.toolInput).length > 0) {
    return syncBindingPermissions(step);
  }
  const binding = inferToolBinding(step, options);
  return syncBindingPermissions({
    ...step,
    tool: binding.tool,
    toolInput: binding.toolInput,
    availableTools: step.availableTools?.length
      ? step.availableTools
      : [binding.tool],
  });
}

function syncBindingPermissions(step: PlanStep): PlanStep {
  const perms = new Set(step.requiredPermissions ?? ["read"]);
  if (step.tool === "shell_run") perms.add("shell");
  if (step.tool === "write_file" || step.tool === "apply_patch") perms.add("write");
  return { ...step, requiredPermissions: [...perms] as PlanStep["requiredPermissions"] };
}

function inferToolBinding(
  step: PlanStep,
  options: BindPlanToolsOptions,
): { tool: string; toolInput: Record<string, unknown> } {
  const text = `${step.title} ${step.objective ?? ""} ${step.description ?? ""}`.toLowerCase();
  const contextPath = pickPath(step, options.defaultReadPath);

  if (step.requiredPermissions.includes("shell") || /\b(npm|node|test|运行|执行命令|shell)\b/.test(text)) {
    return {
      tool: "shell_run",
      toolInput: { command: inferShellCommand(text) },
    };
  }

  if (
    step.requiredPermissions.includes("write") ||
    /\b(写|修改|补丁|patch|apply|覆盖|实现|新增|创建|新建)\b/.test(text)
  ) {
    const path = contextPath ?? "README.md";
    if (/\b(patch|补丁|替换|修改)\b/.test(text) && options.registry.get("apply_patch")) {
      return {
        tool: "apply_patch",
        toolInput: {
          path,
          search: "",
          replace: `// plan step ${step.id}: ${step.title}\n`,
        },
      };
    }
    if (options.registry.get("write_file")) {
      const content = [
        `// Generated by planToolBinder for step ${step.id}`,
        `// ${step.title}`,
        step.objective ? `// ${step.objective}` : "",
        "",
      ]
        .filter(Boolean)
        .join("\n");
      return {
        tool: "write_file",
        toolInput: { path, content },
      };
    }
    return {
      tool: "apply_patch",
      toolInput: { path, search: "", replace: `// ${step.id}\n` },
    };
  }

  if (/\b(扫描|scan|索引|index)\b/.test(text) && options.registry.get("project_scan")) {
    return { tool: "project_scan", toolInput: { root: ".", maxDepth: 2 } };
  }

  if (/\b(搜索|search|定位|locate)\b/.test(text)) {
    const query = extractSearchQuery(step) ?? step.title.slice(0, 80);
    if (options.registry.get("locate_relevant_files")) {
      return { tool: "locate_relevant_files", toolInput: { goal: query, limit: 8 } };
    }
    return { tool: "search_text", toolInput: { query, root: "src", limit: 20 } };
  }

  if (/\b(列出|list|目录)\b/.test(text)) {
    return { tool: "list_files", toolInput: { root: ".", recursive: false, limit: 100 } };
  }

  if (/\b(git|diff|变更)\b/.test(text) && options.registry.get("git_diff")) {
    return { tool: "git_diff", toolInput: contextPath ? { path: contextPath } : {} };
  }

  const readPath = contextPath ?? options.defaultReadPath ?? "package.json";
  return { tool: "read_file", toolInput: { path: readPath } };
}

function pickPath(step: PlanStep, fallback?: string): string | undefined {
  for (const item of step.requiredContext ?? []) {
    const normalized = normalizeCandidatePath(item);
    if (normalized) return normalized;
  }
  const fromText = extractPathFromText(`${step.description ?? ""} ${step.title}`);
  return fromText ?? fallback;
}

function normalizeCandidatePath(value: string): string | undefined {
  const trimmed = value.trim();
  if (!trimmed) return undefined;
  if (/\.[a-z0-9]{1,8}$/i.test(trimmed) || trimmed.includes("/")) {
    return trimmed.replace(/\\/g, "/");
  }
  return undefined;
}

function extractPathFromText(text: string): string | undefined {
  const match = text.match(
    /(?:^|[\s`'"(（])([\w./-]+\.(?:ts|tsx|js|jsx|json|md|py|go|rs|css|html|yml|yaml))(?:$|[\s`'")）])/i,
  );
  return match?.[1]?.replace(/\\/g, "/");
}

function extractSearchQuery(step: PlanStep): string | undefined {
  const fromObjective = step.objective?.trim();
  if (fromObjective && fromObjective.length >= 3) return fromObjective;
  return step.title.trim() || undefined;
}

function inferShellCommand(text: string): string {
  if (/\btypecheck\b/.test(text)) return "npm run typecheck";
  if (/\btest\b|测试/.test(text)) return "npm test";
  if (/\bbuild\b|构建/.test(text)) return "npm run build";
  return "node -v";
}
