/* This file is generated by scripts/generate-ui-component-catalog.mjs. */
import type { FeatureModuleDefinition } from './module-contract';

import { agentPlanModule } from '@renderer/modules/agent-plan';
import { agentStatusModule } from '@renderer/modules/agent-status';
import { chatModule } from '@renderer/modules/chat';
import { fileExplorerModule } from '@renderer/modules/file-explorer';
import { logsModule } from '@renderer/modules/logs';
import { permissionsModule } from '@renderer/modules/permissions';
import { productivityModule } from '@renderer/modules/productivity';
import { runtimeHealthModule } from '@renderer/modules/runtime-health';
import { sessionActivityModule } from '@renderer/modules/session-activity';
import { settingsModule } from '@renderer/modules/settings';
import { terminalModule } from '@renderer/modules/terminal';
import { toolOutputModule } from '@renderer/modules/tool-output';

const DEFINITIONS = Object.freeze([
  agentPlanModule,
  agentStatusModule,
  chatModule,
  fileExplorerModule,
  logsModule,
  permissionsModule,
  productivityModule,
  runtimeHealthModule,
  sessionActivityModule,
  settingsModule,
  terminalModule,
  toolOutputModule,
]);

export function uiComponentDefinitions(): readonly FeatureModuleDefinition[] {
  return DEFINITIONS;
}
