/* This file is generated by scripts/generate-agent-component-catalog.mjs. */
import type { ComponentDefinition } from '@ariadne/component-contracts';

import component0 from './components/command-entity/component.js';
import component1 from './components/conversation/component.js';
import component2 from './components/execution/component.js';
import component3 from './components/inbox/component.js';
import component4 from './components/persistence/component.js';
import component5 from './components/productivity/component.js';
import component6 from './components/projection/component.js';
import component7 from './components/run-control/component.js';
import component8 from './components/skills-human/component.js';
import component9 from './components/subagent-interrupt/component.js';
import component10 from './components/tool-result-detail/component.js';

const DEFINITIONS = Object.freeze([
  component0,
  component1,
  component2,
  component3,
  component4,
  component5,
  component6,
  component7,
  component8,
  component9,
  component10
]);

export function agentCoreComponentDefinitions(): readonly ComponentDefinition[] {
  return DEFINITIONS;
}
