/* This file is generated by scripts/generate-speech-component-catalog.mjs. */
import type { ComponentDefinition } from '@ariadne/component-contracts';

import component0 from './components/agent-bridge/component';
import component1 from './components/core/component';
import component2 from './components/kws/component';
import component3 from './components/renderer-bridge/component';
import component4 from './components/sidecar/component';
import component5 from './components/stt/component';
import component6 from './components/tts/component';
import component7 from './components/voice-pack/component';

const DEFINITIONS = Object.freeze([
  component0,
  component1,
  component2,
  component3,
  component4,
  component5,
  component6,
  component7,
]);

export function speechComponentDefinitions(): readonly ComponentDefinition[] {
  return DEFINITIONS;
}
