/* This file is generated by scripts/generate-runtime-capability-catalog.mjs. */
import type { RuntimeCapabilityProvider } from './RuntimeCapabilityProvider.js';

import component0 from './components/agent-control/component.js';
import component1 from './components/agent-control-services/component.js';
import component2 from './components/extensions/component.js';
import component3 from './components/first-party-tools/component.js';
import component4 from './components/instructions/component.js';
import component5 from './components/runtime-kernel/component.js';

const COMPONENTS = Object.freeze([
  component0,
  component1,
  component2,
  component3,
  component4,
  component5,
]);

export function productionRuntimeCapabilityProviders(): readonly RuntimeCapabilityProvider[] {
  return Object.freeze(COMPONENTS.flatMap((providers) => providers));
}
